export const LABORATORY_EVENTS = {
  ORDER_CREATED: 'LABORATORY_ORDER_CREATED',
  ORDER_COMPLETED: 'LABORATORY_ORDER_COMPLETED',
  ORDER_CANCELLED: 'LABORATORY_ORDER_CANCELLED',
};

export const RADIOLOGY_EVENTS = {
  STUDY_CREATED: 'RADIOLOGY_STUDY_CREATED',
  STUDY_COMPLETED: 'RADIOLOGY_STUDY_COMPLETED',
  STUDY_CANCELLED: 'RADIOLOGY_STUDY_CANCELLED',
};

export const WORKFLOW_EVENTS = {
  APPOINTMENT_CONFIRMED: 'APPOINTMENT_CONFIRMED',
  ARRIVAL_REGISTERED: 'ARRIVAL_REGISTERED',
  ENCOUNTER_OPENED: 'ENCOUNTER_OPENED',
};
