export const COUNTRY_POLICIES = {
  DEFAULT: {
    requireRegistryMatch: true,
    maxClaimsPerPatientPerYear: 50,
    maxFutureServiceDays: 2,
    rejectOnRegistryMismatch: true,
    rejectOnUnverifiedHospital: true,
    rejectOnProviderMismatch: true,
    rejectOnUnaccreditedProcedure: false,
  },
  KE: {
    requireRegistryMatch: true,
    maxClaimsPerPatientPerYear: 60,
    maxFutureServiceDays: 2,
    rejectOnRegistryMismatch: true,
    rejectOnUnverifiedHospital: true,
    rejectOnProviderMismatch: true,
    rejectOnUnaccreditedProcedure: false,
  },
};

export const DEFAULT_CLAIM_RULES = [
  {
    country: "",
    ruleType: "MAX_PER_WINDOW",
    procedureCode: "OPEN_HEART_SURGERY",
    maxPerWindow: 1,
    windowDays: 365,
    severity: "HIGH",
    notes: "Open-heart surgery should not repeat within a year.",
  },
  {
    country: "",
    ruleType: "MAX_PER_WINDOW",
    procedureCategory: "DELIVERY",
    maxPerWindow: 1,
    windowDays: 270,
    severity: "HIGH",
    notes: "Childbirth limited to 1 per 9 months.",
  },
  {
    country: "",
    ruleType: "GENDER_ONLY",
    procedureCategory: "DELIVERY",
    allowedGenders: ["FEMALE"],
    severity: "HIGH",
    notes: "Delivery claims only valid for female patients.",
  },
  {
    country: "",
    ruleType: "AGE_LIMIT",
    procedureCategory: "DELIVERY",
    minAge: 10,
    maxAge: 55,
    severity: "HIGH",
    notes: "Delivery claims only valid for typical reproductive age range.",
  },
  {
    country: "",
    ruleType: "COOLDOWN_DAYS",
    procedureCode: "C_SECTION",
    cooldownDays: 180,
    severity: "MEDIUM",
    notes: "C-section cooldown across repeated procedures.",
  },
  {
    country: "",
    ruleType: "MAX_PER_WINDOW",
    procedureCategory: "CARDIAC_SURGERY",
    maxPerWindow: 2,
    windowDays: 365,
    severity: "HIGH",
    notes: "Cardiac surgeries are rare within a year.",
  },
];
