import fs from 'fs';
import path from 'path';
import process from 'process';

const root = process.cwd();
const name = process.argv[2];

if (!name) {
  console.error('Usage: pnpm runtime:init <name>');
  process.exit(1);
}

const runtimeDir = path.join(root, 'runtimes', name);
if (fs.existsSync(runtimeDir)) {
  console.error(`Runtime already exists: ${name}`);
  process.exit(1);
}

const structure = [
  'runtime',
  'repositories',
  'contracts',
  'policies',
  'workers',
  'events',
  'tests',
  'docs',
];

for (const folder of structure) {
  fs.mkdirSync(path.join(runtimeDir, folder), { recursive: true });
}

const manifest = {
  name,
  owner: 'backend-platform',
  version: '0.1.0',
  maturity: 'In Progress',
  dependencies: [],
  states: ['Pending', 'Completed', 'Cancelled'],
  eventsPublished: [],
  eventsConsumed: [],
  repositories: [],
  routes: [],
  controllers: [],
  policies: [],
  apiRoutes: [],
  databaseCollections: [],
  requiredTests: ['unit', 'integration', 'api'],
  documentation: ['README.md'],
  releaseStatus: 'In Progress',
};

fs.writeFileSync(path.join(runtimeDir, 'runtime.json'), JSON.stringify(manifest, null, 2) + '\n');
fs.writeFileSync(path.join(runtimeDir, 'README.md'), `# ${name}\n\nThis runtime was generated by the platform scaffold.\n`);
fs.writeFileSync(path.join(runtimeDir, 'runtime', 'README.md'), 'Runtime implementation placeholder.\n');
fs.writeFileSync(path.join(runtimeDir, 'tests', 'README.md'), 'Runtime tests placeholder.\n');
fs.writeFileSync(path.join(runtimeDir, 'docs', 'README.md'), 'Runtime docs placeholder.\n');

console.log(`Created runtime scaffold for ${name}`);
