import PDFDocument from "pdfkit";
import crypto from "crypto";

export const generateCourtPDF = (title, data, meta = {}) => {
  const doc = new PDFDocument({ margin: 50 });
  const chunks = [];

  doc.on("data", (chunk) => chunks.push(chunk));

  doc.fontSize(18).text(title, { align: "center" });
  doc.moveDown();

  doc.fontSize(10).text(`Generated At: ${new Date().toISOString()}`);
  doc.text(`Hospital ID: ${meta.hospital}`);
  doc.text(`Generated By: ${meta.generatedBy}`);
  doc.moveDown();

  doc.fontSize(12).text(JSON.stringify(data, null, 2));
  doc.moveDown();

  const hash = crypto
    .createHash("sha256")
    .update(JSON.stringify(data))
    .digest("hex");

  doc.fontSize(10).text(`Evidence Hash (SHA-256): ${hash}`);
  doc.text("This document is system-generated and tamper-evident.");

  doc.end();

  return new Promise((resolve) => {
    doc.on("end", () => {
      resolve({
        buffer: Buffer.concat(chunks),
        hash,
      });
    });
  });
};
