export const governancePermissions = {
  home: ["SYSTEM_ADMIN", "SUPER_ADMIN", "DEVELOPER", "GOVERNMENT_ADMIN", "GOVERNMENT_REGULATOR", "GOVERNMENT_AUDITOR", "GOVERNMENT_INSPECTOR", "GOVERNMENT_ANALYST"],
  claims: ["SYSTEM_ADMIN", "SUPER_ADMIN", "DEVELOPER", "GOVERNMENT_REGULATOR", "GOVERNMENT_ADMIN", "GOVERNMENT_AUDITOR", "GOVERNMENT_INSPECTOR", "GOVERNMENT_ANALYST"],
  registry: ["SYSTEM_ADMIN", "SUPER_ADMIN", "DEVELOPER"],
  patientIdentity: ["SYSTEM_ADMIN", "SUPER_ADMIN", "DEVELOPER"],
  fraud: ["SYSTEM_ADMIN", "SUPER_ADMIN"],
  regulatoryReports: ["SYSTEM_ADMIN", "SUPER_ADMIN", "DEVELOPER", "HOSPITAL_ADMIN"],
  countyCommand: ["SYSTEM_ADMIN", "SUPER_ADMIN", "DEVELOPER"],
  verification: ["SYSTEM_ADMIN", "SUPER_ADMIN", "DEVELOPER"],
};

export default governancePermissions;
