export const ROLES = Object.freeze({
  SUPER_ADMIN: "SUPER_ADMIN",
  HOSPITAL_ADMIN: "HOSPITAL_ADMIN",
  DOCTOR: "DOCTOR",
  NURSE: "NURSE",
  LAB_TECH: "LAB_TECH",
  PHARMACIST: "PHARMACIST",
  PATIENT: "PATIENT",
  GUEST: "GUEST",
});
