export const ROLES = Object.freeze({
  SUPER_ADMIN: "SUPER_ADMIN",
  HOSPITAL_ADMIN: "HOSPITAL_ADMIN",
  DOCTOR: "DOCTOR",
  NURSE: "NURSE",
  LAB_TECH: "LAB_TECH",
  PHARMACIST: "PHARMACIST",
  SECURITY_ADMIN: "SECURITY_ADMIN",
  SECURITY_OFFICER: "SECURITY_OFFICER",
  HR_MANAGER: "HR_MANAGER",
  PAYROLL_OFFICER: "PAYROLL_OFFICER",
  PATIENT: "PATIENT",
  GUEST: "GUEST",
});
