export const FEATURE_CODES = {
  APPOINTMENT_BOOKING: "APPOINTMENT_BOOKING",
  LAB_TEST: "LAB_TEST",
  PRESCRIPTION: "PRESCRIPTION",
  PHARMACY_DISPENSE: "PHARMACY_DISPENSE",
  AI_CHAT: "AI_CHAT",
  AI_DIAGNOSIS: "AI_DIAGNOSIS",
  AI_TRIAGE: "AI_TRIAGE",
  VOICE_DICTATION: "VOICE_DICTATION",
  OCR_DOCUMENT_SCAN: "OCR_DOCUMENT_SCAN",
  VIDEO_CONSULTATION: "VIDEO_CONSULTATION",
  PATIENT_SMS: "PATIENT_SMS",
  EMAIL_NOTIFICATION: "EMAIL_NOTIFICATION",
  WHATSAPP_NOTIFICATION: "WHATSAPP_NOTIFICATION",
  INTER_HOSPITAL_TRANSFER: "INTER_HOSPITAL_TRANSFER",
  CLOUD_STORAGE_GB: "CLOUD_STORAGE_GB",
  CUSTOM: "CUSTOM",
};

export const PREMIUM_FEATURES = new Set([
  FEATURE_CODES.AI_CHAT,
  FEATURE_CODES.AI_DIAGNOSIS,
  FEATURE_CODES.AI_TRIAGE,
  FEATURE_CODES.VOICE_DICTATION,
  FEATURE_CODES.OCR_DOCUMENT_SCAN,
  FEATURE_CODES.PATIENT_SMS,
  FEATURE_CODES.EMAIL_NOTIFICATION,
  FEATURE_CODES.WHATSAPP_NOTIFICATION,
  FEATURE_CODES.VIDEO_CONSULTATION,
  FEATURE_CODES.CLOUD_STORAGE_GB,
]);

export const FEATURE_CODE_ALIASES = {
  SMS: FEATURE_CODES.PATIENT_SMS,
  VOICE: FEATURE_CODES.VOICE_DICTATION,
  OCR: FEATURE_CODES.OCR_DOCUMENT_SCAN,
  STORAGE: FEATURE_CODES.CLOUD_STORAGE_GB,
  VIDEO: FEATURE_CODES.VIDEO_CONSULTATION,
  AI_TRIAGE: FEATURE_CODES.AI_TRIAGE,
  AI_CHAT: FEATURE_CODES.AI_CHAT,
  AI_DIAGNOSIS: FEATURE_CODES.AI_DIAGNOSIS,
};
