export const WORKFLOW = {
  CREATED: "CREATED",
  CONSULTING: "CONSULTING",

  LAB_ORDERED: "LAB_ORDERED",
  LAB_COMPLETED: "LAB_COMPLETED",

  PHARMACY_ORDERED: "PHARMACY_ORDERED",
  DISPENSED: "DISPENSED",

  BILLED: "BILLED",
  PAID: "PAID",

  CLOSED: "CLOSED",
};
