const ROLE_ALIASES = Object.freeze({
  SUPERADMIN: "SUPER_ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
  SYSTEMADMIN: "SYSTEM_ADMIN",
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
  DEVELOPER: "DEVELOPER",
  HOSPITALADMIN: "HOSPITAL_ADMIN",
  HOSPITAL_ADMIN: "HOSPITAL_ADMIN",
  HOSPITALADMINASSISTANT: "HOSPITAL_ADMIN_ASSISTANT",
  HOSPITAL_ADMIN_ASSISTANT: "HOSPITAL_ADMIN_ASSISTANT",
  ADMINASSISTANT: "HOSPITAL_ADMIN_ASSISTANT",
  DOCTOR: "DOCTOR",
  SURGEON: "SURGEON",
  NURSE: "NURSE",
  LABTECH: "LAB_TECH",
  LAB_TECH: "LAB_TECH",
  PHARMACIST: "PHARMACIST",
  SECURITYOFFICER: "SECURITY_OFFICER",
  SECURITY_OFFICER: "SECURITY_OFFICER",
  SECURITYADMIN: "SECURITY_ADMIN",
  SECURITY_ADMIN: "SECURITY_ADMIN",
  HRMANAGER: "HR_MANAGER",
  HR_MANAGER: "HR_MANAGER",
  PAYROLLOFFICER: "PAYROLL_OFFICER",
  PAYROLL_OFFICER: "PAYROLL_OFFICER",
  CHW: "COMMUNITY_HEALTH_WORKER",
  COMMUNITYHEALTHWORKER: "COMMUNITY_HEALTH_WORKER",
  COMMUNITY_HEALTH_WORKER: "COMMUNITY_HEALTH_WORKER",
  RADIOLOGIST: "RADIOLOGIST",
  THERAPIST: "THERAPIST",
  RECEPTIONIST: "RECEPTIONIST",
  GOVERNMENTREGULATOR: "GOVERNMENT_REGULATOR",
  GOVERNMENT_REGULATOR: "GOVERNMENT_REGULATOR",
  GOVERNMENTAUDITOR: "GOVERNMENT_AUDITOR",
  GOVERNMENT_AUDITOR: "GOVERNMENT_AUDITOR",
  GOVERNMENTADMIN: "GOVERNMENT_ADMIN",
  GOVERNMENT_ADMIN: "GOVERNMENT_ADMIN",
  GOVERNMENTINSPECTOR: "GOVERNMENT_INSPECTOR",
  GOVERNMENT_INSPECTOR: "GOVERNMENT_INSPECTOR",
  GOVERNMENTANALYST: "GOVERNMENT_ANALYST",
  GOVERNMENT_ANALYST: "GOVERNMENT_ANALYST",
  PATIENT: "PATIENT",
  GUEST: "GUEST",
});

export function normalizeRole(role) {
  if (typeof role !== "string") return "";

  const normalized = role.trim().replace(/[\s-]+/g, "_").toUpperCase();
  const compact = normalized.replaceAll("_", "");

  return ROLE_ALIASES[normalized] || ROLE_ALIASES[compact] || normalized;
}
